# Generated by Django 2.0.4 on 2018-04-23 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default=None, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(default=None, max_length=100)),
                ('comments', models.TextField()),
            ],
        ),
    ]
