# Generated by Django 2.0.4 on 2018-04-25 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='address',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
